In [2]:
import numpy as np
import pandas as pd 
import seaborn as sns
from matplotlib import pyplot as plt

%matplotlib inline
plt.style.use("ggplot")

In [3]:
np.*add*?

In [4]:
%%timeit
x = 10

10000000 loops, best of 3: 21 ns per loop


In [5]:
w = 5
w += 1
w + 5

11

In [6]:
%history -n 1-2

   1:
import numpy as np
import pandas as pd 
import seaborn as sns
from matplotlib import pyplot as plt

%matplotlib inline
plt.style.use("ggplot")
   2:
import numpy as np
import pandas as pd 
import seaborn as sns
from matplotlib import pyplot as plt

%matplotlib inline
plt.style.use("ggplot")


In [7]:
def divide(a, b):
    return a/b

In [8]:
divide(1, 0)

ZeroDivisionError: division by zero

In [ ]:
%debug

In [9]:
l = [1, 2, 3]
ls = [str(i) for i in l]
lm = l + ls
print(lm)

[1, 2, 3, '1', '2', '3']


In [10]:
al = np.array(l)

In [11]:
als = np.array(ls)

In [12]:
alm = np.array(lm)

In [13]:
alm

array(['1', '2', '3', '1', '2', '3'],
      dtype='<U11')

In [14]:
alm.astype(int)

array([1, 2, 3, 1, 2, 3])

In [15]:
np.arange(1, 101).reshape(2, 2, 5, 5)

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20],
         [ 21,  22,  23,  24,  25]],

        [[ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40],
         [ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50]]],


       [[[ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60],
         [ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75]],

        [[ 76,  77,  78,  79,  80],
         [ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]]]])

In [16]:
np.empty((3, 3, 3))

array([[[  1.26592800e-311,   8.49792911e-322,   0.00000000e+000],
        [  0.00000000e+000,   1.26470949e-311,   2.03889433e+180],
        [  4.82337723e+228,   4.56317366e-144,   5.83001600e+199]],

       [[  7.48468178e+251,   1.71352438e+214,   1.17149199e+214],
        [  3.90674185e+233,   6.99196359e+228,   8.03704417e-095],
        [  8.37170554e-144,   1.05135742e-153,   2.04418456e+214]],

       [[  2.18183932e+243,   2.19993033e-152,   8.55412711e+136],
        [  1.67818232e-152,   1.75300480e+243,   4.07262648e-144],
        [  7.67127212e+151,   7.48463356e+251,   1.03941590e-314]]])

In [17]:
print("itemsize: ", alm.itemsize)
print("size: ", alm.size)
print("nbytes: ", alm.nbytes)

itemsize:  44
size:  6
nbytes:  264


**Complex numbers**

In [18]:
3 - 4j

(3-4j)

In [19]:
x = np.arange(0, 6)
np.multiply.outer(np.power(2, x), np.power(2, x))

array([[   1,    2,    4,    8,   16,   32],
       [   2,    4,    8,   16,   32,   64],
       [   4,    8,   16,   32,   64,  128],
       [   8,   16,   32,   64,  128,  256],
       [  16,   32,   64,  128,  256,  512],
       [  32,   64,  128,  256,  512, 1024]], dtype=int32)

In [20]:
x = np.arange(1, 6)
np.power.outer(x, x)

array([[   1,    1,    1,    1,    1],
       [   2,    4,    8,   16,   32],
       [   3,    9,   27,   81,  243],
       [   4,   16,   64,  256, 1024],
       [   5,   25,  125,  625, 3125]], dtype=int32)

**sum vs np.sum***

In [21]:
x = np.arange(1, 10).reshape(3, 3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
sum(x), np.sum(x)

(array([12, 15, 18]), 45)

**agregate along axis**

In [23]:
x = np.random.permutation(np.arange(1, 28)).reshape(3, 3, 3)
x

array([[[13,  7, 25],
        [15, 17,  6],
        [22,  8,  1]],

       [[26, 11, 20],
        [14, 18, 23],
        [ 2,  5, 24]],

       [[12,  4, 27],
        [19,  9, 16],
        [10,  3, 21]]])

In [24]:
x.min(axis=0)

array([[12,  4, 20],
       [14,  9,  6],
       [ 2,  3,  1]])

In [25]:
x.min(axis=1)

array([[13,  7,  1],
       [ 2,  5, 20],
       [10,  3, 16]])

In [26]:
x.min(axis=2)

array([[ 7,  6,  1],
       [11, 14,  2],
       [ 4,  9,  3]])

In [27]:
a = np.arange(1, 10).reshape(3, 3)

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
mean = a.mean(0)
mean

array([ 4.,  5.,  6.])

In [30]:
x = np.random.RandomState(0).randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [36]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

In [41]:
row = np.array([0, 1, 2])[:, np.newaxis]
col = np.array([2, 1, 3])
[row, col]

[array([[0],
        [1],
        [2]]), array([2, 1, 3])]

In [42]:
X[row, col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

<font color="red">**Redo fancy indexing**</font>

In [45]:
X.sort()
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])