In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns
from matplotlib import pyplot as plt

%matplotlib inline
plt.style.use("ggplot")

In [2]:
np.*add*?

In [3]:
%%timeit
x = 10

10000000 loops, best of 3: 28 ns per loop


In [4]:
w = 5
w += 1
w + 5

11

In [5]:
%history -n 1-2

   1:
import numpy as np
import pandas as pd 
import seaborn as sns
from matplotlib import pyplot as plt

%matplotlib inline
plt.style.use("ggplot")
   2: np.*add*?


In [6]:
def divide(a, b):
    return a/b

In [7]:
divide(1, 0)

ZeroDivisionError: division by zero

In [8]:
%debug

> <ipython-input-6-7a89fd6f7045>(2)divide()
      1 def divide(a, b):
----> 2     return a/b

ipdb> exit()


In [9]:
l = [1, 2, 3]
ls = [str(i) for i in l]
lm = l + ls
print(lm)

[1, 2, 3, '1', '2', '3']


In [10]:
al = np.array(l)

In [11]:
als = np.array(ls)

In [12]:
alm = np.array(lm)

In [13]:
alm

array(['1', '2', '3', '1', '2', '3'],
      dtype='<U11')

In [14]:
alm.astype(int)

array([1, 2, 3, 1, 2, 3])

In [15]:
np.arange(1, 101).reshape(2, 2, 5, 5)

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20],
         [ 21,  22,  23,  24,  25]],

        [[ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40],
         [ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50]]],


       [[[ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60],
         [ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75]],

        [[ 76,  77,  78,  79,  80],
         [ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]]]])

In [16]:
np.empty((3, 3, 3))

array([[[  6.23042070e-307,   4.67296746e-307,   1.69121096e-306],
        [  8.01099926e-307,   6.23060065e-307,   8.45593934e-307],
        [  7.56593017e-307,   1.11261027e-306,   1.11261502e-306]],

       [[  1.42410839e-306,   7.56597770e-307,   6.23059726e-307],
        [  1.42418987e-306,   1.24610859e-306,   9.34609790e-307],
        [  1.06809996e-306,   7.56602523e-307,   2.22521510e-306]],

       [[  1.05700515e-307,   1.11261774e-306,   1.29060871e-306],
        [  8.34424766e-308,   8.34445138e-308,   1.37959129e-306],
        [  1.02360528e-306,   8.45610230e-307,   1.25936558e-311]]])

In [17]:
print("itemsize: ", alm.itemsize)
print("size: ", alm.size)
print("nbytes: ", alm.nbytes)

itemsize:  44
size:  6
nbytes:  264


**Complex numbers**

In [18]:
3 - 4j

(3-4j)

In [19]:
x = np.arange(0, 6)
np.multiply.outer(np.power(2, x), np.power(2, x))

array([[   1,    2,    4,    8,   16,   32],
       [   2,    4,    8,   16,   32,   64],
       [   4,    8,   16,   32,   64,  128],
       [   8,   16,   32,   64,  128,  256],
       [  16,   32,   64,  128,  256,  512],
       [  32,   64,  128,  256,  512, 1024]], dtype=int32)

In [20]:
x = np.arange(1, 6)
np.power.outer(x, x)

array([[   1,    1,    1,    1,    1],
       [   2,    4,    8,   16,   32],
       [   3,    9,   27,   81,  243],
       [   4,   16,   64,  256, 1024],
       [   5,   25,  125,  625, 3125]], dtype=int32)

**sum vs np.sum***

In [21]:
x = np.arange(1, 10).reshape(3, 3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
sum(x), np.sum(x)

(array([12, 15, 18]), 45)

**agregate along axis**

In [23]:
x = np.random.permutation(np.arange(1, 28)).reshape(3, 3, 3)
x

array([[[ 2, 23,  7],
        [24, 27, 14],
        [10, 15,  6]],

       [[18,  5, 20],
        [16, 25, 12],
        [21, 11, 22]],

       [[ 1, 17,  4],
        [26,  9, 19],
        [13,  3,  8]]])

In [24]:
x.min(axis=0)

array([[ 1,  5,  4],
       [16,  9, 12],
       [10,  3,  6]])

In [25]:
x.min(axis=1)

array([[ 2, 15,  6],
       [16,  5, 12],
       [ 1,  3,  4]])

In [26]:
x.min(axis=2)

array([[ 2, 14,  6],
       [ 5, 12, 11],
       [ 1,  9,  3]])

In [27]:
a = np.arange(1, 10).reshape(3, 3)

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
mean = a.mean(0)
mean

array([ 4.,  5.,  6.])

In [30]:
x = np.random.RandomState(0).randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [31]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

In [33]:
row = np.array([0, 1, 2])[:, np.newaxis]
col = np.array([2, 1, 3])
[row, col]

[array([[0],
        [1],
        [2]]), array([2, 1, 3])]

In [34]:
X[row, col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

<font color="red">**Redo fancy indexing**</font>

In [35]:
X.sort()
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

02.09 Structured Data NumPy

In [9]:
people = np.zeros(3, dtype=[("name", 'U10'), ('age', 'i4')])

In [10]:
people

array([('', 0), ('', 0), ('', 0)],
      dtype=[('name', '<U10'), ('age', '<i4')])

In [11]:
people['name'] = ['Bob', 'Tom', 'Amy']

In [12]:
people

array([('Bob', 0), ('Tom', 0), ('Amy', 0)],
      dtype=[('name', '<U10'), ('age', '<i4')])

03.00 Introduction to Pandas

In [13]:
pd?

03.01 Introducing Pandas Objects

In [23]:
pd.Series([1, 10, 5, 50], index=['a', 'b', 'c', 'd'])

a     1
b    10
c     5
d    50
dtype: int64

In [21]:
pd.Series({'a': 1,
           'b': 2,
           'c': 3})

a    1
b    2
c    3
dtype: int64

In [26]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])  # creates series by choosing only index values from dictionary and keeps their
                                                # specified order

3    c
2    a
dtype: object

In [27]:
pd.DataFrame([{'a': 1, 'b': 3}, {'a': 10}])

a    b
0   1  3.0
1  10  NaN

In [36]:
pd.DataFrame(np.zeros((3, 2)))

0    1
0  0.0  0.0
1  0.0  0.0
2  0.0  0.0

In [45]:
pd.DataFrame(np.zeros(2, dtype=[('X', 'i8'), ('Y', 'f8'), ('Z', 'i8')]))

X    Y  Z
0  0  0.0  0
1  0  0.0  0

In [46]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [47]:
indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [48]:
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [49]:
indA ^ indB

Int64Index([1, 2, 9, 11], dtype='int64')

03.02 Data Indexing and Selection

Among these, slicing may be the source of the most confusion. Notice that when slicing with an explicit index (i.e., data['a':'c']), the final index is included in the slice, while when slicing with an implicit index (i.e., data[0:2]), the final index is excluded from the slice.

In [51]:
data = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4})
data

a    1
b    2
c    3
d    4
dtype: int64

In [52]:
data['a':'c']

a    1
b    2
c    3
dtype: int64

In [53]:
data[0:2]

a    1
b    2
dtype: int64

---

In [68]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [69]:
# explicit index when indexing
data[1]

'a'

In [70]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

---

In [63]:
data = pd.Series(['a', 'b', 'c', 'd', 'e'], index=[1, 2, 3, 4, 5])
data

1    a
2    b
3    c
4    d
5    e
dtype: object

In [64]:
data.loc[1]  # for explicit index

'a'

In [65]:
data.iloc[1]  # for implicit index

'b'

In [66]:
data.loc[1:3]

1    a
2    b
3    c
dtype: object

In [67]:
data.iloc[1:3]

2    b
3    c
dtype: object

---

In particular, you should avoid the temptation to try column assignment via attribute (i.e., use data['pop'] = z rather than data.pop = z)

---

03.03 Operations in Pandas

In [73]:
rng = np.random.RandomState(0)
df = pd.DataFrame(rng.randint(0, 10, (3, 2)), columns=["A", "B"])
df

A  B
0  5  0
1  3  3
2  7  9

In [74]:
np.square(df)

A   B
0  25   0
1   9   9
2  49  81

In [75]:
s1 = pd.Series([1, 3, 5], index=["a", "b", "c"])
s2 = pd.Series([2, 2, 2], index=["a", "c", "d"])

In [76]:
s1 + s2

a    3.0
b    NaN
c    7.0
d    NaN
dtype: float64

In [80]:
s1.add(s2, fill_value=0)

a    3.0
b    3.0
c    7.0
d    2.0
dtype: float64

In [81]:
df

A  B
0  5  0
1  3  3
2  7  9

In [85]:
df.stack?

---

03.04 Missing Values

In [91]:
1e-3 + 1e6

1000000.001

In [92]:
1 + np.nan

nan

In [99]:
vals = [1, 2, 3, np.nan]
np.sum(vals)

nan

In [100]:
np.nansum(vals)

6.0

In [102]:
np.nanmean(vals) # ignores nans

2.0

In [103]:
pd.Series([1, np.nan, 'hello', None]).isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [123]:
df = pd.DataFrame([[1,      np.nan, np.nan],
                   [np.nan, np.nan,      5],
                   [np.nan, np.nan,      6],
                   [3,      np.nan,      3]])

In [124]:
df.dropna(how='all', axis=1)

0    2
0  1.0  NaN
1  NaN  5.0
2  NaN  6.0
3  3.0  3.0

In [130]:
df.dropna(axis="columns", thresh=2) # thresh - require that many non-NA values

0    2
0  1.0  NaN
1  NaN  5.0
2  NaN  6.0
3  3.0  3.0

---
03.05-Hierarchical-Indexing

In [131]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]

In [148]:
df = pd.Series(populations, index=pd.MultiIndex.from_tuples(index))
df

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [141]:
df.unstack()

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [142]:
df.unstack().stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [149]:
df = pd.DataFrame({"total": df,
    "under18": [9267089, 9284094,
                4687374, 4318033,
                5906301, 6879014]})

In [150]:
df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [183]:
# multiindex for rows and columns

h_df = pd.DataFrame(np.random.randint(0, 20, size=(6, 4)),  
                   columns=pd.MultiIndex.from_product([["Test A", "Test B"], ["seg 1", "seg 2"]], names=["test", "segment"]),
                   index=pd.MultiIndex.from_product([["Alice", "Bob", "John"], [2010, 2015]]))
h_df

test       Test A       Test B      
segment     seg 1 seg 2  seg 1 seg 2
Alice 2010     17     5     13     1
      2015     10     9      3     7
Bob   2010     14    19     19    11
      2015      2     3      4     8
John  2010      6     7     15    10
      2015      5     0      5    14

In [184]:
h_df.loc["Bob", 2010]["Test A"]

segment
seg 1    14
seg 2    19
Name: (Bob, 2010), dtype: int32

In [185]:
h_df.loc["Alice":"Bob"]

test       Test A       Test B      
segment     seg 1 seg 2  seg 1 seg 2
Alice 2010     17     5     13     1
      2015     10     9      3     7
Bob   2010     14    19     19    11
      2015      2     3      4     8