# Numpy

In [1]:
import numpy as np

**Dot product**

\begin{equation}
a \bullet b = a^Tb = \sum_{d=1}^D a_d b_d
\end{equation}

\begin{equation}
a \bullet b = |a||b|\cos \theta_{ab}
\end{equation}

In [3]:
a = np.array([2, 1])
b = np.array([1, 2])

In [4]:
a * b  # element-wise multiplication

array([2, 2])

In [5]:
np.sum(a * b)

4

In [6]:
(a * b).sum()

4

In [7]:
np.dot(a, b)

4

In [8]:
a.dot(b)

4

In [9]:
b.dot(a)

4

**Calculating angle**

\begin{equation}
\cos \theta_{ab} = \frac{a \bullet b}{|a||b|}
\end{equation}

In [10]:
amag = np.sqrt((a * a).sum())
amag

2.2360679774997898

In [11]:
amag = np.linalg.norm(a)
amag

2.2360679774997898

In [13]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
angle = np.arccos(cosangle)
angle

0.6435011087932847

**Vectors in np**

In [2]:
v1 = np.array([1, 2, 3])

In [4]:
v2 = np.array([4, 5, 6])

In [5]:
v3 = np.array([[4],
               [5],
               [6]])

In [15]:
v1 @ v2

32

In [52]:
v1.dot(v2)

32

In [51]:
v1 @ v3

array([32])

In [17]:
v1.reshape(1, 3) @ v3

array([[32]])

In [55]:
v1 * v3

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

**Creating arrays**

In [25]:
np.zeros((3, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [26]:
np.ones((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [27]:
np.random.random((3, 3)) # uniform distribution

array([[ 0.58299155,  0.43975457,  0.55743127],
       [ 0.33342258,  0.86392986,  0.83070263],
       [ 0.95547074,  0.97057278,  0.08643564]])

In [30]:
# gaussian
G = np.random.randn(3, 3)  # randn takes individual dimensions as integers not a tuple of dimensions
G

array([[-0.04591687, -0.28463255,  2.85340472],
       [-0.02729743,  0.20960274,  0.86896192],
       [-0.76263761, -0.28145959,  0.02701184]])

In [31]:
G.mean()

0.28411524112379277

In [33]:
G.var() # variance

0.99554309447185396

**Matrix Products**

In [39]:
A = np.ones((3, 3))
B = np.ones((3, 3)) * 2
B

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [40]:
A * B  # element-wise multiplication

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [41]:
A @ B  # matrix multiplication (python 3)

array([[ 6.,  6.,  6.],
       [ 6.,  6.,  6.],
       [ 6.,  6.,  6.]])

In [42]:
A.dot(B) # matrix multiplication

array([[ 6.,  6.,  6.],
       [ 6.,  6.,  6.],
       [ 6.,  6.,  6.]])

**Other Matrix Operations**

- matrix inverse

In [43]:
A = np.array([[1, 2], 
              [3, 4]])
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [45]:
np.round(A @ Ainv)

array([[ 1.,  0.],
       [ 0.,  1.]])

- matrix determinant

In [46]:
np.linalg.det(A)

-2.0000000000000004

- matrix diagonal

In [48]:
np.diag(A)

array([1, 4])

In [49]:
np.diag([1, 2, 3])  # creates matrix with given diagonal

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

- outer product

In [57]:
a = np.array([1, 2])
b = np.array([3, 4])
np.outer(a, b)

array([[3, 4],
       [6, 8]])

- inner product (dot product)

In [59]:
np.inner(a, b)

11

- matrix trace

In [62]:
np.trace(A) == np.diag(A).sum()

True

- covariance

In [64]:
X = np.random.randn(100, 3)  # gausian distributed datapoints

In [66]:
np.cov(X).shape

(100, 100)

In [69]:
cov = np.cov(X.T)  # if you calculate covariance of a data matrix you have to transpose it first
cov

array([[ 0.73549527, -0.13653131, -0.02760957],
       [-0.13653131,  0.81280357, -0.05875389],
       [-0.02760957, -0.05875389,  0.96547663]])

- eigenvalues and eigenvectors
np.eig(C) or np.eigh(C)
eigh is for symmetric($A = A^T$) and Hermitian ($A = A^H$(conjugate transpose of $A$)) matrices.

In [70]:
np.linalg.eigh(cov)

(array([ 0.62253628,  0.90370291,  0.98753628]),
 array([[ 0.7759969 , -0.62022102,  0.11469396],
        [ 0.60831112,  0.6878717 , -0.39596729],
        [ 0.16669251,  0.377039  ,  0.91107365]]))

In [71]:
np.linalg.eig(cov)

(array([ 0.62253628,  0.90370291,  0.98753628]),
 array([[-0.7759969 , -0.62022102,  0.11469396],
        [-0.60831112,  0.6878717 , -0.39596729],
        [-0.16669251,  0.377039  ,  0.91107365]]))

**Solving a Linear System**

Problem: $Ax = b$

Solution: $A^{-1}Ax = x = A^{-1}b$

- Is a system of D equations and D unknowns
- A is DxD, assume it is invertible
- We have all the tools we need to solve this already:
    - Matrix inverse
    - Matrix multipy (dot)

In [74]:
A = np.array([[1, 2],
              [3, 4]])

In [75]:
b = np.array([1, 2])

In [83]:
x = np.linalg.inv(A).dot(b), 4
x

(array([  2.22044605e-16,   5.00000000e-01]), 4)

In [84]:
x = np.linalg.solve(A, b)
x

array([ 0. ,  0.5])

- **always use solve(), never use the inverse method. It is both more efficient and more accurate**

**Word Problem**

$x_1 + x_2 = 2200$ <br>
$1.5x_1 + 4x_2 =5500$

$\begin{pmatrix} 
1 & 1   \\ 
1.5 & 4
\end{pmatrix} 
\begin{pmatrix} x_1 \\ x_2 \end{pmatrix}
=
\begin{pmatrix} 2200 \\ 5050 \end{pmatrix}
$

In [87]:
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])

In [91]:
x = np.linalg.solve(A, b)
x

array([ 1500.,   700.])