In [3]:
import numpy as np
import pandas as pd 
import seaborn as sns
from matplotlib import pyplot as plt

%matplotlib inline
plt.style.use("ggplot")

In [3]:
np.*add*?

In [9]:
%%timeit
x = 10

10000000 loops, best of 3: 21.3 ns per loop


In [11]:
w = 5
w += 1
w + 5

11

In [14]:
%history -n 1-2

   1:
import numpy as np
import pandas as pd 
import seaborn as sns
from matplotlib import pyplot as plt

%matplotlib inline
plt.style.use("ggplot")
   2: np.*rand*?


In [15]:
def divide(a, b):
    return a/b

In [16]:
divide(1, 0)

ZeroDivisionError: division by zero

In [17]:
%debug

> <ipython-input-15-7a89fd6f7045>(2)divide()
      1 def divide(a, b):
----> 2     return a/b

ipdb> print(a)
1
ipdb> print(b)
0
ipdb> exit()


In [21]:
l = [1, 2, 3]
ls = [str(i) for i in l]
lm = l + ls
print(lm)

[1, 2, 3, '1', '2', '3']


In [19]:
al = np.array(l)

In [22]:
als = np.array(ls)

In [23]:
alm = np.array(lm)

In [24]:
alm

array(['1', '2', '3', '1', '2', '3'],
      dtype='<U11')

In [27]:
alm.astype(int)

array([1, 2, 3, 1, 2, 3])

In [34]:
np.arange(1, 101).reshape(2, 2, 5, 5)

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20],
         [ 21,  22,  23,  24,  25]],

        [[ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40],
         [ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50]]],


       [[[ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60],
         [ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75]],

        [[ 76,  77,  78,  79,  80],
         [ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]]]])

In [36]:
np.empty((3, 3, 3))

array([[[  1.34383271e-311,   8.49792911e-322,   0.00000000e+000],
        [  0.00000000e+000,   4.55071971e+198,   6.96410748e+252],
        [  8.03408341e-095,   5.50028887e+247,   2.15799222e+243]],

       [[  2.64986851e+180,   9.00495240e+130,   9.11034336e+140],
        [  9.00495264e+130,   8.58412521e+183,   1.81450396e-152],
        [  2.91809879e-014,   2.25870842e+137,   1.02908498e+213]],

       [[  5.04621361e+180,   7.49779533e+247,   3.88625532e+285],
        [  5.37993879e+151,   1.67751550e+243,   4.54814392e-144],
        [  5.83001600e+199,   7.48468178e+251,   2.21211623e+214]]])

In [37]:
print("itemsize: ", alm.itemsize)
print("size: ", alm.size)
print("nbytes: ", alm.nbytes)

itemsize:  44
size:  6
nbytes:  264


**Complex numbers**

In [2]:
3 - 4j

(3-4j)

In [9]:
x = np.arange(0, 6)
np.multiply.outer(np.power(2, x), np.power(2, x))

array([[   1,    2,    4,    8,   16,   32],
       [   2,    4,    8,   16,   32,   64],
       [   4,    8,   16,   32,   64,  128],
       [   8,   16,   32,   64,  128,  256],
       [  16,   32,   64,  128,  256,  512],
       [  32,   64,  128,  256,  512, 1024]], dtype=int32)

In [11]:
x = np.arange(1, 6)
np.power.outer(x, x)

array([[   1,    1,    1,    1,    1],
       [   2,    4,    8,   16,   32],
       [   3,    9,   27,   81,  243],
       [   4,   16,   64,  256, 1024],
       [   5,   25,  125,  625, 3125]], dtype=int32)

**sum vs np.sum***

In [40]:
x = np.arange(1, 10).reshape(3, 3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
sum(x), np.sum(x)

(array([12, 15, 18]), 45)

**agregate along axis**

In [36]:
x = np.random.permutation(np.arange(1, 28)).reshape(3, 3, 3)
x

array([[[24, 18,  8],
        [10, 25, 11],
        [ 4, 12, 21]],

       [[20,  3, 16],
        [23,  2,  1],
        [ 9, 19, 17]],

       [[ 5, 15,  6],
        [27, 13, 14],
        [22,  7, 26]]])

In [37]:
x.min(axis=0)

array([[ 5,  3,  6],
       [10,  2,  1],
       [ 4,  7, 17]])

In [38]:
x.min(axis=1)

array([[ 4, 12,  8],
       [ 9,  2,  1],
       [ 5,  7,  6]])

In [39]:
x.min(axis=2)

array([[ 8, 10,  4],
       [ 3,  1,  9],
       [ 5, 13,  7]])

In [53]:
a = np.arange(1, 10).reshape(3, 3)

In [55]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
mean = a.mean(0)
mean

array([ 4.,  5.,  6.])